name: DSS3
channels:
  - pytorch
  - pytorch3d
  - conda-forge
  - bottler
  - defaults
  - plotly
dependencies:
  - python=3.8
  - cudatoolkit=10.2
  - pytorch::pytorch=1.6.0
  - pytorch::torchvision
  - fvcore
  - jupyter
  - scikit-image
  - matplotlib
  - imageio
  - pytorch3d::pytorch3d
  - pip
  - tensorboard=1.15.0
  - trimesh
  - cython
  - pyyaml
  - pandas
  - easydict
  - nvidiacub
  - plotly
  - pip:
    - pymeshlab==0.1.8
    - https://data.pyg.org/whl/torch-1.6.0%2Bcu102/torch_cluster-1.5.9-cp38-cp38-linux_x86_64.whl